# Setup
title:               JP Voogt
tagline:             'A Jekyll theme'
description:         'South African Data Tinkerer and <a href="https://twitter.com/microsoft" target="_blank">@microsoft</a> Fanboy | <a href="https://twitter.com/dataplatformjhb" target="_blank">@dataplatformjhb</a> leader | Formula 1 enthusiasts and Father | (He/Him)'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y


  